# Версия docker-compose
version: '2'
# Список наших сервисов (контейнеров)
services:
    nginx:
        # используем последний стабильный образ nginx
        image: nginx:1.17.8
        container_name: nginx1
        restart: always
        # маршрутизируем порты
        ports:
            - "80:80"
            - "4435:443"
        # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
        volumes:
            #WorkingDirectory
            - ./www:/var/www
            #Логи
            - ./logs/nginx:/var/log/nginx
            #Конфигурационные файлы
            - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./conf/nginx/hosts:/etc/nginx/conf.d
        # nginx должен общаться с php контейнером
        links:
            - php
        networks:
            my_bridge:
                ipv4_address: 172.10.1.10
    php:
        # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
        build: ./images/php
        container_name: php1
        restart: always
        # этот образ будет общаться с mysql
        links:
            - mysql
        # монтируем директорию с проектами
        volumes:
            - ./www:/var/www
            - ./conf/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
            - ./conf/php/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./conf/php/php.ini:/usr/local/etc/php/php.ini
            - ./conf/php/40-custom.ini:/usr/local/etc/php/conf.d/40-custom.ini
        networks:
            my_bridge:
                ipv4_address: 172.10.1.20

    mysql:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        
        container_name: mysql1
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
           # - ./conf/mysql/my.cnf:/etc/mysql/my.cnf
            - ./logs/mysql:/var/log/mysql
        # задаем пароль для root пользователя
        environment:
            MYSQL_ROOT_PASSWORD: 12345
        networks:
            my_bridge:
                ipv4_address: 172.10.1.30
            
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
          UPLOAD_LIMIT: 1G
        container_name: phpmyadmin1
        restart: always
        links: 
          - mysql:db
        ports:
          - 8501:80
        volumes:
          - ./conf/phpmyadmin:/var/www/html/libraries
        environment:
          MYSQL_ROOT_PASSWORD: 12345
          UPLOAD_LIMIT: 300M
        depends_on:
          - mysql
        networks:
            my_bridge:
                ipv4_address: 172.10.1.40
networks:
    my_bridge:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.10.1.0/16
                  gateway: 172.10.1.1
